from setuptools import setup, find_packages

with open("README.md", "r") as f:
    long_description = f.read()

setup(
    name="custom_theme_v15",
    version="0.0.1",
    description="Custom Theme App for Frappe/ERPNext v15 - customizable variants and overrides",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="Generated by ChatGPT",
    packages=find_packages(),
    zip_safe=False,
    include_package_data=True,
)
